# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  # - 0.5
  - 0.6
  - nightly
matrix:
    allow_failures:
        # - julia: 0.5  #TODO: make apply only to versions of package targeted at Julia v-0.6?
        - julia: nightly
notifications:
    email: false
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("Temporal")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("Temporal")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
